// Read-only ABI coordinates of this compiled notorch library.
// Copyright (C) 2026 Oleg Ataeff & Arianna Method contributors
// SPDX-License-Identifier: LGPL-3.0-or-later
#include "spa_binding.h"
#include "spa_agent.h"
#include <string.h>

typedef struct { const char *key; size_t value; } spa_abi_entry;
#define CONST(x) {#x, (size_t)(x)}
#define STRUCT(t) {#t ".sizeof", sizeof(t)}, {#t ".alignof", _Alignof(t)}
#define FIELD(t, f) {#t "." #f ".offset", offsetof(t, f)}, \
    {#t "." #f ".sizeof", sizeof(((t *)0)->f)}

static const spa_abi_entry layout[] = {
    CONST(NT_SPA_AGENT_VERSION),
    CONST(NT_SPA_AGENT_PERCEPTION_VERSION),
    CONST(NT_SPA_AGENT_REWARD_VERSION),
    CONST(NT_SPA_EXPERIENCE_VERSION),
    CONST(NT_SPA_AGENT_EMBED),
    CONST(NT_SPA_AGENT_FEATURES),
    CONST(NT_SPA_AGENT_HIDDEN),
    CONST(NT_SPA_AGENT_ACTIONS),
    CONST(NT_SPA_AGENT_PARAMETERS),
    CONST(NT_SPA_AGENT_HISTORY),
    CONST(NT_SPA_AGENT_MAX_SENTENCES),
    CONST(NT_SPA_AGENT_MAX_DIM),
    CONST(NT_SPA_AGENT_NO_SOURCE),
    CONST(NT_SPA_COMPARISON_MAX_HORIZON),
    CONST(NT_SPA_COMPARISON_MAX_REPEATS),
    CONST(NT_SPA_AGENT_DISABLED),
    CONST(NT_SPA_AGENT_LEGACY),
    CONST(NT_SPA_AGENT_LEARNED),
    CONST(NT_SPA_KEEP),
    CONST(NT_SPA_RESEED_LEFT),
    CONST(NT_SPA_RESEED_RIGHT),
    {"sizeof.float", sizeof(float)},
    {"sizeof.double", sizeof(double)},
    {"sizeof.nt_spa_action_kind", sizeof(nt_spa_action_kind)},
    {"sizeof.nt_spa_agent_mode", sizeof(nt_spa_agent_mode)},
    STRUCT(nt_spa_action),
    FIELD(nt_spa_action, kind),
    FIELD(nt_spa_action, target),
    FIELD(nt_spa_action, source),
    STRUCT(nt_spa_metrics),
    FIELD(nt_spa_metrics, local_connectedness),
    FIELD(nt_spa_metrics, global_connectedness),
    FIELD(nt_spa_metrics, coherence),
    FIELD(nt_spa_metrics, novelty),
    FIELD(nt_spa_metrics, repetition),
    FIELD(nt_spa_metrics, collapse),
    FIELD(nt_spa_metrics, continuity),
    STRUCT(nt_spa_consequence),
    FIELD(nt_spa_consequence, before),
    FIELD(nt_spa_consequence, after),
    FIELD(nt_spa_consequence, regeneration_cost),
    STRUCT(nt_spa_agent_config),
    FIELD(nt_spa_agent_config, mode),
    FIELD(nt_spa_agent_config, seed),
    FIELD(nt_spa_agent_config, learning_rate),
    FIELD(nt_spa_agent_config, imitation_rate),
    FIELD(nt_spa_agent_config, exploration),
    FIELD(nt_spa_agent_config, memory_decay),
    FIELD(nt_spa_agent_config, reward_weights),
    FIELD(nt_spa_agent_config, cost_weight),
    STRUCT(nt_spa_observation),
    FIELD(nt_spa_observation, embedding),
    FIELD(nt_spa_observation, connectedness),
    FIELD(nt_spa_observation, left_similarity),
    FIELD(nt_spa_observation, right_similarity),
    FIELD(nt_spa_observation, coherence),
    FIELD(nt_spa_observation, novelty),
    FIELD(nt_spa_observation, repetition),
    FIELD(nt_spa_observation, phase_lock),
    FIELD(nt_spa_observation, sentence_score),
    FIELD(nt_spa_observation, mean_sentence_score),
    FIELD(nt_spa_observation, temperature),
    FIELD(nt_spa_observation, sentence_index),
    FIELD(nt_spa_observation, sentence_count),
    FIELD(nt_spa_observation, reseed_count),
    STRUCT(nt_spa_policy),
    FIELD(nt_spa_policy, w1),
    FIELD(nt_spa_policy, b1),
    FIELD(nt_spa_policy, w2),
    FIELD(nt_spa_policy, b2),
    STRUCT(nt_spa_decision),
    FIELD(nt_spa_decision, observation),
    FIELD(nt_spa_decision, features),
    FIELD(nt_spa_decision, hidden),
    FIELD(nt_spa_decision, scores),
    FIELD(nt_spa_decision, action),
    FIELD(nt_spa_decision, sequence),
    FIELD(nt_spa_decision, rng_before),
    FIELD(nt_spa_decision, explored),
    STRUCT(nt_spa_receipt),
    FIELD(nt_spa_receipt, sequence),
    FIELD(nt_spa_receipt, action),
    FIELD(nt_spa_receipt, sentence_count),
    FIELD(nt_spa_receipt, consequence),
    FIELD(nt_spa_receipt, reward),
    FIELD(nt_spa_receipt, predicted),
    FIELD(nt_spa_receipt, error),
    FIELD(nt_spa_receipt, learned),
    STRUCT(nt_spa_agent),
    FIELD(nt_spa_agent, version),
    FIELD(nt_spa_agent, perception_version),
    FIELD(nt_spa_agent, reward_version),
    FIELD(nt_spa_agent, config),
    FIELD(nt_spa_agent, config_hash),
    FIELD(nt_spa_agent, policy),
    FIELD(nt_spa_agent, rng),
    FIELD(nt_spa_agent, decisions),
    FIELD(nt_spa_agent, observations),
    FIELD(nt_spa_agent, updates),
    FIELD(nt_spa_agent, imitation_updates),
    FIELD(nt_spa_agent, cancelled),
    FIELD(nt_spa_agent, memory_observations),
    FIELD(nt_spa_agent, history_count),
    FIELD(nt_spa_agent, history_head),
    FIELD(nt_spa_agent, history),
    FIELD(nt_spa_agent, ema_reward),
    FIELD(nt_spa_agent, ema_connectedness),
    FIELD(nt_spa_agent, ema_novelty),
    FIELD(nt_spa_agent, pending),
    FIELD(nt_spa_agent, pending_decision),
    STRUCT(nt_spa_experience),
    FIELD(nt_spa_experience, version),
    FIELD(nt_spa_experience, sentence_index),
    FIELD(nt_spa_experience, sentence_count),
    FIELD(nt_spa_experience, source_life_hash),
    FIELD(nt_spa_experience, features),
    STRUCT(nt_spa_alternative),
    FIELD(nt_spa_alternative, action),
    FIELD(nt_spa_alternative, consequence),
    STRUCT(nt_spa_comparison),
    FIELD(nt_spa_comparison, source_life_hash),
    FIELD(nt_spa_comparison, horizon),
    FIELD(nt_spa_comparison, action_mask),
    FIELD(nt_spa_comparison, alternatives),
    STRUCT(nt_spa_readout),
    FIELD(nt_spa_readout, action),
    FIELD(nt_spa_readout, action_mask),
    FIELD(nt_spa_readout, scores),
    STRUCT(nt_spa_comparison_receipt),
    FIELD(nt_spa_comparison_receipt, source_life_hash),
    FIELD(nt_spa_comparison_receipt, horizon),
    FIELD(nt_spa_comparison_receipt, action_mask),
    FIELD(nt_spa_comparison_receipt, learning_rate),
    FIELD(nt_spa_comparison_receipt, rewards),
    FIELD(nt_spa_comparison_receipt, targets),
    FIELD(nt_spa_comparison_receipt, scores_before),
    FIELD(nt_spa_comparison_receipt, scores_after),
    FIELD(nt_spa_comparison_receipt, loss_before),
    FIELD(nt_spa_comparison_receipt, loss_after),
    STRUCT(nt_spa_conditioned_receipt),
    FIELD(nt_spa_conditioned_receipt, comparison),
    FIELD(nt_spa_conditioned_receipt, scale_floor),
    FIELD(nt_spa_conditioned_receipt, scale),
};

uint32_t nt_spa_binding_version(void) { return 1u; }

size_t nt_spa_binding_layout(const char *key) {
    size_t i;
    if (!key) return SIZE_MAX;
    for (i = 0; i < sizeof(layout) / sizeof(layout[0]); ++i)
        if (strcmp(key, layout[i].key) == 0) return layout[i].value;
    return SIZE_MAX;
}
