#!/usr/bin/env python3
"""Regenerate sampling_reference.h with Python integers and Decimal weights.

Development-only reference; check_sampling compiles the checked-in C fixture
and needs no Python. Run from the repository root and review the changed file.
"""
from decimal import Decimal, localcontext
from pathlib import Path

MASK32 = (1 << 32) - 1
MASK64 = (1 << 64) - 1
SEEDS = [0, 1, 42, 16777215, 0x0123456789ABCDEF, MASK64]
BOUNDS = [1, 3, 7, 65537, 16777216, 2147483649, MASK32]
TEMPERATURES = [0.25, 0.5, 1, 2, 4]
WEIGHTS = [0, 1, 2, 5, 13]


def word(state):
    bits = (((state // (1 << 18)) ^ state) // (1 << 27)) & MASK32
    rotation = state // (1 << 59)
    rotated = ((bits // (1 << rotation)) |
               (bits * (1 << ((32 - rotation) % 32)))) & MASK32
    return ((state * 6364136223846793005 + 109) & MASK64), rotated


def seeded(seed):
    state, _ = word(0)
    state, _ = word((state + seed) & MASK64)
    return state


def categorical(raw, temperature):
    with localcontext() as ctx:
        ctx.prec = 80
        exponent = Decimal(1) / Decimal(temperature)
        # Direct powers, independent of the implementation's log/max scaling.
        weights = [Decimal(w) ** exponent if w else Decimal(0) for w in WEIGHTS]
        target = Decimal(raw) / Decimal(1 << 32) * sum(weights)
        cumulative = Decimal(0)
        for index, weight in enumerate(weights):
            cumulative += weight
            if target < cumulative:
                return index
        raise AssertionError("Decimal categorical did not select an index")


lines = [
    "/* Generated by tests/make_sampling_reference.py; do not hand-edit. */",
    "/* Seed groups: 64 mixed operations each; weights = {0,1,2,5,13}. */",
    "typedef struct {",
    "    uint64_t seed, state;",
    "    uint32_t bound, integer;",
    "    float temperature, uniform;",
    "    int op, reset;",
    "} sampling_reference_case;",
    "static const sampling_reference_case sampling_reference[] = {",
]
for seed in SEEDS:
    state = seeded(seed)
    for cycle in range(16):
        for op in range(4):
            integer, uniform, bound, temperature = 0, 0.0, 0, 1
            state, raw = word(state)
            if op == 0:
                integer = raw
            elif op == 1:
                uniform = (raw // 256) / (1 << 24)
            elif op == 2:
                bound = BOUNDS[cycle % len(BOUNDS)]
                # Keep the largest divisible suffix of all 2^32 values.
                first_accepted = (1 << 32) % bound
                while raw < first_accepted:
                    state, raw = word(state)
                integer = raw % bound
            else:
                temperature = TEMPERATURES[cycle % len(TEMPERATURES)]
                integer = categorical(raw, temperature)
            lines.append(
                f"    {{UINT64_C(0x{seed:016x}), UINT64_C(0x{state:016x}), "
                f"UINT32_C({bound}), UINT32_C({integer}), {float(temperature).hex()}f, "
                f"{uniform.hex()}f, {op}, {int(cycle == 0 and op == 0)}}},"
            )
lines.append("};")
Path(__file__).with_name("sampling_reference.h").write_text("\n".join(lines) + "\n")
print(f"wrote {len(SEEDS) * 16 * 4} independent mixed-operation reference cases")
