#!/usr/bin/env python3
"""Independent Python binary64 MLP and integer-PCG normal reference.

Regenerate: python3 tests/numerical_values_reference.py > tests/numerical_values_reference.h
The C test consumes the committed header and has no Python dependency.
"""
import math
import struct

MASK = (1 << 64) - 1


def word(state):
    nxt = (state * 6364136223846793005 + 109) & MASK
    x = (((state >> 18) ^ state) >> 27) & 0xFFFFFFFF
    r = state >> 59
    return nxt, ((x >> r) | (x << ((-r) & 31))) & 0xFFFFFFFF


def seed(value):
    state, _ = word(0)
    state, _ = word((state + value) & MASK)
    return state


def f32(value):
    return struct.unpack("f", struct.pack("f", value))[0]


def literal(value):
    return float(value).hex() + "f"


print("/* Generated by numerical_values_reference.py; independent Python references. */")
print("typedef struct { uint64_t before, after; float value; } normal_value_case;")
print("static const normal_value_case normal_value_reference[] = {")
for start in [0, 0x07FFFE0000000000] + [seed(s) for s in (0, 1, 42, 73, 16777215, MASK)]:
    state = start
    for _ in range(32):
        before = state
        state, a = word(state)
        state, b = word(state)
        value = math.sqrt(-2 * math.log((a + 1) / 4294967297)) * math.cos(2 * math.pi * b / 4294967296)
        print(f"    {{UINT64_C({before}), UINT64_C({state}), {literal(f32(value))}}},")
print("};")

x = [f32(v) for v in (0.01, 0.7, 0.2, 0.8, 0.7)]
params = [f32(((i * 7) % 19 - 9) * 0.037) for i in range(57)]
targets = [f32(v) for v in (0.7, 0.1, 0.9, 0.3, 0.5, 0.0, 1.0, 0.2)]
print("static const float value_mlp_input[5] = {" + ", ".join(map(literal, x)) + "};")
print("static const float value_mlp_initial[57] = {" + ", ".join(map(literal, params)) + "};")
print("static const float value_mlp_targets[8] = {" + ", ".join(map(literal, targets)) + "};")
print("typedef struct { float prediction, loss, params[57]; } mlp_value_step;")
print("static const mlp_value_step value_mlp_reference[] = {")
for step in range(32):
    hidden = [math.tanh(sum((params[r * 6 + c] * x[c] for c in range(5)), params[r * 6 + 5])) for r in range(8)]
    prediction = math.tanh(sum((params[48 + r] * hidden[r] for r in range(8)), params[56]))
    diff = prediction - targets[step % 8]
    dz2 = 2 * diff * (1 - prediction * prediction)
    gradient = [0.0] * 57
    for r in range(8):
        gradient[48 + r] = dz2 * hidden[r]
        dz1 = dz2 * params[48 + r] * (1 - hidden[r] * hidden[r])
        for c in range(5):
            gradient[r * 6 + c] = dz1 * x[c]
        gradient[r * 6 + 5] = dz1
    gradient[56] = dz2
    params = [p - f32(0.01) * g for p, g in zip(params, gradient)]
    print("    {" + literal(prediction) + ", " + literal(diff * diff) + ", {" + ", ".join(map(literal, params)) + "}},")
print("};")
