#!/usr/bin/env python3
"""Generate byte-length/padding-boundary SHA-256 fixtures with hashlib."""
import argparse
import hashlib
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path(__file__).with_name("sha256_reference.h"))
    args = parser.parse_args()
    lengths = list(range(257)) + [511, 512, 513, 1000, 4096, 65536, 1000000]
    lines = ["/* Generated by tests/reference_sha256.py using Python hashlib.",
             " * Input byte i = (i * 53 + i / 7 + 173) modulo 256. */",
             "#ifndef NT_SHA256_REFERENCE_H", "#define NT_SHA256_REFERENCE_H",
             "static const struct { size_t bytes; const char *hex; } sha256_references[] = {"]
    for n in lengths:
        source = bytes((i * 53 + i // 7 + 173) & 255 for i in range(n))
        lines.append(f'    {{{n},"{hashlib.sha256(source).hexdigest()}"}},')
    lines += ["};", "#endif", ""]
    args.output.write_text("\n".join(lines))
    print(f"wrote {len(lengths)} SHA-256 fixtures")


if __name__ == "__main__":
    main()
